blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/astoreyai/claude-oauth-auth/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Vulnerability
    url: https://github.com/astoreyai/claude-oauth-auth/security/advisories/new
    about: Report security vulnerabilities privately (DO NOT create a public issue)
