name: Documentation Issue
description: Report unclear, missing, or incorrect documentation
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve our documentation! Clear documentation is essential for a great developer experience.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation is this issue about?
      options:
        - README
        - API Reference
        - Guide/Tutorial
        - Code Examples
        - Docstrings
        - Configuration
        - Installation
        - Contributing Guide
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing documentation
        - Unclear/confusing documentation
        - Incorrect/outdated documentation
        - Broken link
        - Typo or grammar error
        - Missing code example
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the documentation issue located?
      placeholder: |
        - File: README.md, line 42
        - URL: https://...
        - Section: "Authentication Flow"
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the documentation currently say (if applicable)?
      placeholder: Quote the current text or describe what's there now
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: What's Unclear or Missing?
      description: Describe what's confusing, missing, or incorrect
      placeholder: |
        The documentation doesn't explain...
        I expected to find information about...
        This section is confusing because...
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: |
        The documentation should explain...
        It would be helpful to add an example showing...
        This could be clarified by...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code/Content
      description: If suggesting new documentation, provide an example of what you'd like to see
      placeholder: |
        ```python
        # Example showing how to...
        ```

        Or provide text content you think would be clearer
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to related documentation, examples, or external resources
      placeholder: |
        - Similar documentation in project X: ...
        - Relevant RFC/specification: ...
        - Related issue: #...
    validations:
      required: false

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who is this documentation primarily for?
      options:
        - New users/beginners
        - Intermediate users
        - Advanced users
        - Contributors
        - All users
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that would help us improve the documentation
      placeholder: |
        I was trying to accomplish...
        I looked for this information in...
        This would have saved me X hours...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to help improve this documentation?
      options:
        - label: I am willing to submit a pull request to fix this
          required: false
        - label: I can help review proposed changes
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this hasn't been reported before
          required: true
        - label: I have checked the latest version of the documentation
          required: false
