name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe what you're trying to accomplish.
      placeholder: I'm frustrated when... / I need to be able to...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like to have a method that...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried... but it doesn't work because...
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and how this feature would help
      placeholder: |
        I'm building an application that...
        This feature would allow me to...
    validations:
      required: true

  - type: textarea
    id: example-code
    attributes:
      label: Example Code
      description: If possible, provide an example of how you envision using this feature
      placeholder: |
        ```python
        from claude_oauth_auth import ClaudeOAuthClient

        client = ClaudeOAuthClient(...)
        # Proposed usage
        result = client.new_feature(...)
        ```
      render: python
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New functionality
        - Enhancement to existing feature
        - Performance improvement
        - Developer experience improvement
        - Documentation improvement
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Important for my use case
        - Medium - Would be nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
      placeholder: |
        - Related to issue #...
        - Similar feature in package X
        - Reference documentation: ...
    validations:
      required: false

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I am willing to submit a pull request for this feature
          required: false
        - label: I can help with testing and feedback
          required: false
        - label: I can help with documentation
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and discussions to ensure this hasn't been requested before
          required: true
        - label: This feature aligns with the project's scope and goals
          required: false
